# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-11 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('location_description', models.CharField(max_length=250)),
                ('quality', models.CharField(max_length=25)),
                ('wifi', models.BooleanField(default=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('hotel_website_price', models.IntegerField(blank=True, null=True)),
                ('makemytrip_price', models.IntegerField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('others_price', models.IntegerField(blank=True, null=True)),
                ('num_stars', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='hotel_image')),
            ],
        ),
    ]
